services:
  users-list:
    build: .
    container_name: users-list
    command:
      [
        'wait-for-it',
        '${POSTGRES_HOST}:${POSTGRES_PORT}',
        '--',
        'npm',
        'run',
        'i_mig_seed_start',
      ]

    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - users-list-network
    env_file:
      - .env

  postgres:
    container_name: users-list-db
    image: postgres
    restart: on-failure
    networks:
      - users-list-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - usersList:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  users-list-network:

volumes:
  usersList:
